server:
  port: 8082

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    enabled: true
    baseUrl: http://opentelemetry-loadbalancer.tracing:9411
    service:
      name: microserviceC
